import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { Providers } from "./providers";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "CRM - Client Administration",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
                <Providers>
                    <div className="md:flex min-h-screen">
                        {/* Sidebar with Fixed Position on Small Screens */}
                        <aside className="md:w-72 xl:w-1/5 bg-gray-800 md:sticky md:top-0 md:h-screen">
                            <Sidebar />
                        </aside>

                        {/* Main Content */}
                        <main className="flex-1 h-screen overflow-y-scroll bg-gray-100 dark:bg-gray-900 p-5 pb-96 md:pb-5">
                            {children}
                        </main>
                    </div>
                </Providers>
			</body>
		</html>
	);
}
