import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { Poppins } from "next/font/google";
import ApolloProvider from "@/components/providers/ApolloProvider";

const poppins = Poppins({
	weight: ["400", "600", "700"], // or whichever weights you need
	subsets: ["latin"],
	variable: "--font-poppins",
});

export const metadata: Metadata = {
	title: "CRM - Client Administration",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${poppins.variable} font-sans antialiased`}>
				<ApolloProvider>
                    {children}
                </ApolloProvider>
			</body>
		</html>
	);
}
